version: '3'
services:
  interactif:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 0.0.0.0:5000:5000
    volumes:
      - ./src:/src/src
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - -p 5000
    environment:
      FLASK_DEBUG: 1
      HOST: "localhost:5000"
      
